---
- name: Install Apache HTTP Server
  ansible.builtin.package:
    name: httpd
    state: present

- name: Start Apache HTTP Server
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
