---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    uses: github-actions-reusable-workflows/ansible-lint/.github/workflows/workflows.yml@main

  handler_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Show uptime
        run: |
          uptime

      - name: Show IPv4 address
        run: |
          hostname -I

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Docker run CentOS8 image sudo installed
        run: docker run -d --privileged --name=centos-stream8 ghcr.io/docker-hub-tm/ansible-test/centos-stream8:latest /sbin/init

      - name: Install galaxy roles
        run: |
          ansible-galaxy install git+https://github.com/${{ github.repository }},${{ github.sha }}

      - name: Execute ansible-playbook command
        run: |
          ansible-playbook -i 'centos-stream8,' \
          -c docker -u ansible tests/test_handler.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PROFILE_TASKS_SORT_ORDER: 'none'
          PROFILE_TASKS_TASK_OUTPUT_LIMIT: '100'
          PY_COLORS: '1'
          TZ: 'Asia/Tokyo'

      - name: Show Ansible version
        run: |
          pip list | grep ansible \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
          ansible --version

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@master

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: |
          yamllint --version \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
